@startuml
class Estudiante{
-matricula: String
--
+Estudiante(nombre: String, edad: int, matricula: String)
+getNombre(): String
+setNombre(nombre: String): void
+getEdad(): int
+setEdad(edad: int): void
+getMatricula(): String
+setMatricula(matricula: String): void
}

abstract class Persona{
-nombre: String
-edad: int

--
+Persona(nombre: String, edad: int)
+getNombre(): String
+setNombre(nombre: String): void
+getEdad(): int
+setEdad(edad: int): void
#mostrarPeso(): int
}
Persona <-- Estudiante
@enduml


